name: bots

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  #push:
  #  branches: [ main ]
  #pull_request:
  #  branches: [ main ]

  schedule:
    - cron: "5 16 * * *"

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - name: Install requirements
        run: |
          pip3 install -r ./requirements.txt
      - name: Run checkin
        run: |
          python3 ./main.py
        env:
          PUSHPLUS_TOKEN: ${{ secrets.PUSHPLUS_TOKEN }}
          SERVER_TOKEN: ${{ secrets.SERVER_TOKEN }}
          QMSG_TOKEN: ${{ secrets.QMSG_TOKEN }}
          QYWECHAT_TOKEN: ${{ secrets.QYWECHAT_TOKEN }}
          DD_TOKEN: ${{ secrets.DD_TOKEN }}
      - uses: gautamkrishnar/keepalive-workflow@master
